### PR TITLE
Time on notes

### PR DESCRIPTION
**Pull request by arno09**

### CODE REVIEW

**Comment by lucasaba** [comment]
Hi @arno09 
I didn't see this. I've just got notified of you closing the pull request.

Do you still want me to merge yout PR ?

**Comment by arno09** [comment]
Sorry @lucasaba this is a mistake, I'm not a regular user of github.
I think I'm going to create my own repository because my needs are specific (and I'll try to rewrite it in CQRS and DDD for fun, once I've added the features I'm missing).
I will quote your repository to indicate that I have drawn heavily on yours, if you don't mind, of course.

**Comment by lucasaba** [comment]
No, absolutely! That would be great. And, do you mind if I merge your code in my repository ? I really like your ideas!

**Comment by arno09** [comment]
You can merge but try it first because I'm not sure that it work fine (there is perhaps bugs). And sorry if I make some mistakes in english, I'm french ;-)

**Pull request closed without merging**
